### ISSUE TITLE
仅适用于usdt对？

### ISSUE THREAD

**Issue by jdk-sal3** [grassroadsZ/spot_grid_web#3]
我有2个问题：

1.我尝试在bnbbtc上使用它，但是“下一个买入”和“下一个卖出”的价格显示相同的值，并且仅显示两位小数。
就我而言，它以非常快的时间（每1或2秒）不间断地以相同的价格水平（0.01）买卖bnbtc。
它无法检测到超过2个十进制数字的价格。
BNBBTC价格具有6个小数位（当前价格为0.011601），并且漫游器仅将其检测为0.01

2.在usdt对上，如果价格快速波动，则无法下达买入或卖出订单，因此跳过了一些买入和卖出。

**Comment by grassroadsZ** [comment]
所有的币对都可以适用,但是精度问题在于自己设置的最小位数

**Comment by jdk-sal3** [comment]
你是正确的...我的错误。 谢谢
